name: betterschool
description: "BetterSchool - A feature-rich client for beste.schule, designed for students and parents."
publish_to: "none"

# 0.1.0 - Auth
# 0.2.0 - Timetable
# 0.3.0 - Grades
# 0.4.0 - Settings
# 0.5.0 - Icon
# 0.6.0 - Further Improvements
# 1.0.0 - First MVVM clean architecture rewrite release
version: 0.2.0

environment:
  sdk: ^3.9.0-0

dependency_overrides:
  analyzer: ^8.2.0

dependencies:
  flutter:
    sdk: flutter

  # state management
  flutter_bloc: ^9.1.1

  # comparing
  equatable: ^2.0.7

  # service locator
  get_it: ^9.2.0

  # date formatter
  intl: ^0.20.2

  # api requests
  retrofit: ^4.9.1
  json_annotation: ^4.9.0
  dio: ^5.9.0

  # logging
  logger: ^2.6.2

  # oauth
  oauth_webauth: ^5.2.0
  oauth2: ^2.0.5

  # token store
  flutter_secure_storage: ^10.0.0

  # caching
  path: ^1.9.1
  sqlite3_flutter_libs: ^0.5.41
  path_provider: ^2.1.5
  sqflite_common_ffi: ^2.4.0
  remote_caching: ^1.0.14

  # date time utils
  in_date_utils: ^1.3.0

  # svg
  flutter_svg: ^2.2.3
  loading_animation_widget: ^1.3.0
  shared_preferences: ^2.5.4

  # settings
  settings_tiles: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  retrofit_generator: ^10.2.0
  build_runner: ^2.10.4
  json_serializable: ^6.11.3

flutter:
  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
